const FILTER_TYPE = 'FILTER_TYPE';
const FILTER_CONDITION = 'FILTER_CONDITION';
const FILTER_ROOMS = 'FILTER_ROOMS';
const FILTER_BATHROOMS = 'FILTER_BATHROOMS';
const FILTER_SIZE = 'FILTER_SIZE';
const FILTER_PRICE = 'FILTER_PRICE';
const FILTER_PET = 'FILTER_PET';
const FILTER_GARDEN = 'FILTER_GARDEN';
const FILTER_AIR_CONDITIONING = 'FILTER_AIR_CONDITIONING';
const FILTER_SWIMMING_POOL = 'FILTER_SWIMMING_POOL';
const FILTER_TERRACE = 'FILTER_TERRACE';
const FILTER_DATE = 'FILTER_DATE';
const GET_PROPERTIES = 'GET_PROPERTIES';

export {
    FILTER_TYPE,
    FILTER_CONDITION,
    FILTER_ROOMS,
    FILTER_BATHROOMS,
    FILTER_SIZE,
    FILTER_PRICE,
    FILTER_PET,
    FILTER_GARDEN,
    FILTER_AIR_CONDITIONING,
    FILTER_SWIMMING_POOL,
    FILTER_TERRACE,
    FILTER_DATE,
    GET_PROPERTIES
}